import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
// import LoadingSpinner from '@/components/LoadingSpinner/loading-spinner'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Zeitgeist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >

        {/* <LoadingProvider> */}
        {/* <div> */}
          {/* <LoadingSpinner /> */}
          
          {children} 
        {/* </div> */}
      </body>
    </html>
  );
}
